[package]
name = "LPC55S28-USB"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usb-device = "0.2.9"
LPC55S28-PAC = { version = "0.1.0", path = "../LPC55S28_PAC" }